- name: "Install haproxy and keepalived"
  become: true
  ansible.builtin.apt:
    name:
      - haproxy
      - keepalived
    state: present

- name: "Create haproxy config directory"
  become: true
  ansible.builtin.file:
    path: /etc/haproxy
    state: directory
    mode: 0755

- name: "Create haproxy config file"
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: "Create keepalived config directory"
  become: true
  ansible.builtin.file:
    path: /etc/keepalived
    state: directory
    mode: 0755

- name: "Create keepalived config file"
  become: true
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644

- name: "Copy keepalived check script"
  become: true
  ansible.builtin.template:
    src: check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    owner: root
    group: root
    mode: 0755

- name: "Enable and start haproxy"
  become: true
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
    enabled: true

- name: "Enable and start keepalived"
  become: true
  ansible.builtin.systemd:
    name: keepalived
    state: reloaded
    enabled: true
